[project]
name = "workflow-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "graphviz>=0.21",
    "langgraph-checkpoint>=2.1.1",
    "langgraph[all]>=0.5.3",
]
